let state=null, selected=null, lastLog=0;
const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,options={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const j=await r.json();if(!r.ok)throw new Error(j.error||'Request failed');return j}
function renderScripts(){const n=document.getElementById('scripts');n.innerHTML='';for(const s of state.scripts){const b=document.createElement('button');b.className='script'+(s.id===selected?' selected':'');b.innerHTML=`${esc(s.label)}<small>${esc(s.id)}</small>`;b.onclick=()=>{selected=s.id;renderScripts();renderFields()};n.appendChild(b)}}
function renderFields(){const s=state.scripts.find(x=>x.id===selected);document.getElementById('title').textContent=s.label;const box=document.getElementById('fields');box.innerHTML='';for(const [key,value] of Object.entries(s.config)){const d=document.createElement('div');const nested=typeof value==='object'&&value!==null;d.className='field'+(nested?' wide':'');const l=document.createElement('label');l.textContent=key;d.appendChild(l);let el;if(key==='mouse_backend'){el=document.createElement('select');for(const option of ['standard','quartz']){const o=document.createElement('option');o.value=option;o.textContent=option==='standard'?'Standard — moves cursor':'Quartz — experimental background click';o.selected=value===option;el.appendChild(o)}}else if(key==='platform'){el=document.createElement('select');for(const option of ['auto','mac','windows']){const o=document.createElement('option');o.value=option;o.textContent=option==='auto'?'Auto detect':option;o.selected=value===option;el.appendChild(o)}}else if(typeof value==='boolean'){el=document.createElement('input');el.type='checkbox';el.checked=value}else if(nested){el=document.createElement('textarea');el.value=JSON.stringify(value,null,2)}else{el=document.createElement('input');el.type=typeof value==='number'?'number':'text';if(typeof value==='number')el.step='any';el.value=value}el.dataset.key=key;el.dataset.type=Array.isArray(value)?'array':typeof value;d.appendChild(el);box.appendChild(d)}updateButtons()}
function collect(){const out={};for(const el of document.querySelectorAll('[data-key]')){let v;if(el.dataset.type==='boolean')v=el.checked;else if(el.dataset.type==='number')v=Number(el.value);else if(el.dataset.type==='object'||el.dataset.type==='array')v=JSON.parse(el.value);else v=el.value;out[el.dataset.key]=v}return out}
async function save(){const config=collect();await api('/api/save',{method:'POST',body:JSON.stringify({id:selected,config})});state.scripts.find(x=>x.id===selected).config=config;flash('Settings saved')}
async function start(){const config=collect();if(config.dry_run===false){const detail=config.mouse_backend==='quartz'?'The experimental Quartz backend will send background click events. RuneLite compatibility is not yet confirmed.':'This automation will move and click the mouse.';if(!confirm('Live mode is enabled. '+detail+' Start it?'))return}await api('/api/start',{method:'POST',body:JSON.stringify({id:selected,config})});state.scripts.find(x=>x.id===selected).config=config;await refreshStatus()}
async function stop(){await api('/api/stop',{method:'POST',body:'{}'});setTimeout(refreshStatus,250)}
function flash(t){const e=document.getElementById('status');e.textContent=t;setTimeout(refreshStatus,900)}
function updateButtons(){const running=state?.process?.running;document.getElementById('start').disabled=running;document.getElementById('stop').disabled=!running}
async function refreshStatus(){const p=await api('/api/status');state.process=p;const e=document.getElementById('status');if(p.running){const s=state.scripts.find(x=>x.id===p.script_id);e.textContent='Running · '+(s?s.label:p.script_id);e.className='status running'}else{e.textContent='Idle';e.className='status'}updateButtons()}
async function pollLogs(){try{const data=await api('/api/logs?after='+lastLog);const e=document.getElementById('logs');for(const l of data.logs){lastLog=l.id;const span=document.createElement('span');span.className=l.kind==='system'?'log-system':'';span.textContent=l.text+'\n';e.appendChild(span)}if(data.logs.length)e.scrollTop=e.scrollHeight}catch{}setTimeout(pollLogs,700)}
async function init(){state=await api('/api/state');selected=state.scripts[0].id;renderScripts();renderFields();refreshStatus();pollLogs()}
document.getElementById('start').onclick=()=>start().catch(e=>alert(e.message));document.getElementById('stop').onclick=()=>stop().catch(e=>alert(e.message));document.getElementById('save').onclick=()=>save().catch(e=>alert('Invalid setting: '+e.message));init();